timezone: America/Denver
encoding: utf-8
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude:
  - README.md
  - LICENSE
  - docker-compose.yml
  - _site/
  - .gitignore
  - .sass-cache/
  - .jekyll-cache/
  - template-bare.html
  - template-layout.html
  - template.md
  - Dockerfile
  - .vs/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "welcome"
    values:
      layout: "welcome"
      course: "CYBER 344"
      quizminutes: 2
  -
    scope:
      path: "slides/*.pptx"
    values:
      viewer: ppt
collections:
  welcome:
    output: true
    permalink: /welcome/:path.html

sass:
  sass_dir: _sass
  
